# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 18:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boundaries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('radius', models.DecimalField(decimal_places=6, max_digits=14)),
                ('origin', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('zone', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('country', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crises', to='boundaries.Country', verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('home_country', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='boundaries.Country', verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('number_of_turns', models.IntegerField(blank=True, default=10, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=2000, null=True)),
                ('crisis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.Crisis')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='games.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('address', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('payroll_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('crisis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scheme', to='games.Crisis')),
                ('donor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schemes', to='games.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('ENTERTAINMENT', 'Entertainment'), ('CLOTHING', 'Clothing'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities')], default='FOOD', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='games.Person')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='games.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=1, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='games.Game')),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='games.Turn'),
        ),
        migrations.AddField(
            model_name='person',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Scheme'),
        ),
        migrations.AddField(
            model_name='person',
            name='transactions',
            field=models.ManyToManyField(related_name='transactions_for', through='games.Transaction', to='games.Person'),
        ),
    ]
