# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='category',
            field=models.CharField(choices=[('FOOD', 'Food'), ('ENTERTAINMENT', 'Entertainment'), ('CLOTHING', 'Clothing'), ('RENT', 'Rent'), ('UTILITIES', 'Utilities')], default='FOOD', max_length=20),
        ),
    ]
