# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20170220_0422'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turn',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
