# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 21:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20170220_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='games.Scheme'),
        ),
    ]
