# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_household_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='games.Household'),
        ),
    ]
