# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20170221_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='games.Scheme'),
        ),
    ]
