# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 08:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20170222_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='games.Vendor'),
        ),
    ]
