# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-22 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_auto_20170222_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
